### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by alistairmcmillan**
Adding Travis CI support

### CODE REVIEW

**Comment by alistairmcmillan** [comment]
Premature. I'll fix this and submit later.

**Comment by cDima** [comment]
Oh I would love travis ci in this project. Was there some issue?

**Comment by alistairmcmillan** [comment]
Almost got it working but not quite. Travis uses Mono to compile .Net software rather than Microsoft's toolchain so it needs a few changes.

Hit the wrong button and opened this PR by accident the other night. Shouldn't be attempting to write code at 3am. :)

**Comment by alistairmcmillan** [comment]
Please remember to revert this PR. :)

**Pull request merged**
